### ISSUE TITLE
bug: ANR when clicking install

### ISSUE THREAD

**Issue by Axelen123** [revanced/revanced-manager-compose#46]
I don't know why right now, but clicking on the install button causes android to think that the app is not responding.

**Comment by CnC-Robert** [comment]
Could it be because you're calling `installApp` from the main thread?

**Comment by Axelen123** [comment]
> Could it be because you're calling `installApp` from the main thread?

I am unsure. This bug did not occur when I initially implemented it.

**Comment by Axelen123** [comment]
@CnC-Robert you were right. It appears `installApp` reads the file to the installer session, but that takes a long time if the apk is 100+ MB like with YT. This bug has been fixed by https://github.com/revanced/revanced-manager-compose/commit/a09e00c7a93786477678949f21965ec8fb5fcbb2
