### ISSUE TITLE
Custom Sources

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-manager-compose#5]

**Comment by alexandreteles** [comment]
@Ushie, please provide at least a basic description of this issue.

**Comment by Axelen123** [comment]
Custom sources are now partially implemented, but there are still quite a few things left:
- [ ] Respect the API url provided by the user
- [ ] UI
- [ ] Deal with loading errors properly
- [ ] Show version info
- [ ] Deal with versioning for local bundles (either use the last modified date as the version or get it from the bundle)
