### ISSUE TITLE
work-runtime bizzare char

### ISSUE THREAD

**Issue by wiiznokes** [ReVanced/revanced-manager-compose#86]
there seems to be a miss character in `libs.versions.toml` file.
```work-runtime = "2.8.1ō"```
should be 2.8.1 i think.
https://mvnrepository.com/artifact/androidx.work/work-runtime-ktx?repo=google

**Comment by Axelen123** [comment]
I am surprised this didn't result in any build failures. I have removed the character from the file. Thank you

**Comment by wiiznokes** [comment]
this is weird indeed
